---
- hosts: all
  gather_facts: yes
  tasks:
  - name: Copy Installer
    win_copy:
      src: ./files/dotnet.exe
      dest: C:\temp\

  - name: Run Microsoft .NET Framework 4.6.1 installer
    raw: C:\temp\dotnet.exe /q /norestart /log C:\tmp\dotnet\dotnet461\log.txt /x86 /x64 /redist
    register: dotnet_install

  - name: Reboot as required by Microsoft .NET Framework 4.6.1 installer
    win_reboot:
  - name: check version
    win_shell: |
       reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP"
       reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\full" /v version
        
tasks:
   - name: CPM installation
     win_command: cmd.exe /c E:\Guru\Cyberark\CPM_install\setup.exe 
     args:
      /q 
      /norestart 
      /log C:\temp\cpminstall\log.txt 
      accepteula='yes' 
      UserName='ExxonMobil'
      Companyname='ExxonMobil' 
      Installdir='F:\\Program Files (x86)\\CyberArk\\' 
      isUpgrade="False" 
      VaultIP='10.129.186.34' 
      Vaultport='1858' 
      Vaultuser='{{VAULT_USERNAME}}' 
      VaultPassword='{{VAULT_PASSWORD}}'
     register: cpm_install  
